package com.smartqueue2.database.orm;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.smartqueue2.database.ormsql.AccountInfo;
import com.smartqueue2.database.ormsql.QueueInfo;
import com.smartqueue2.database.ormsql.QueueInfoBackup;
import com.smartqueue2.database.ormsql.QueueSetInfo;
import com.smartqueue2.database.ormsql.ShopInfo;

import com.smartqueue2.database.orm.AccountInfoDao;
import com.smartqueue2.database.orm.QueueInfoDao;
import com.smartqueue2.database.orm.QueueInfoBackupDao;
import com.smartqueue2.database.orm.QueueSetInfoDao;
import com.smartqueue2.database.orm.ShopInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig accountInfoDaoConfig;
    private final DaoConfig queueInfoDaoConfig;
    private final DaoConfig queueInfoBackupDaoConfig;
    private final DaoConfig queueSetInfoDaoConfig;
    private final DaoConfig shopInfoDaoConfig;

    private final AccountInfoDao accountInfoDao;
    private final QueueInfoDao queueInfoDao;
    private final QueueInfoBackupDao queueInfoBackupDao;
    private final QueueSetInfoDao queueSetInfoDao;
    private final ShopInfoDao shopInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        accountInfoDaoConfig = daoConfigMap.get(AccountInfoDao.class).clone();
        accountInfoDaoConfig.initIdentityScope(type);

        queueInfoDaoConfig = daoConfigMap.get(QueueInfoDao.class).clone();
        queueInfoDaoConfig.initIdentityScope(type);

        queueInfoBackupDaoConfig = daoConfigMap.get(QueueInfoBackupDao.class).clone();
        queueInfoBackupDaoConfig.initIdentityScope(type);

        queueSetInfoDaoConfig = daoConfigMap.get(QueueSetInfoDao.class).clone();
        queueSetInfoDaoConfig.initIdentityScope(type);

        shopInfoDaoConfig = daoConfigMap.get(ShopInfoDao.class).clone();
        shopInfoDaoConfig.initIdentityScope(type);

        accountInfoDao = new AccountInfoDao(accountInfoDaoConfig, this);
        queueInfoDao = new QueueInfoDao(queueInfoDaoConfig, this);
        queueInfoBackupDao = new QueueInfoBackupDao(queueInfoBackupDaoConfig, this);
        queueSetInfoDao = new QueueSetInfoDao(queueSetInfoDaoConfig, this);
        shopInfoDao = new ShopInfoDao(shopInfoDaoConfig, this);

        registerDao(AccountInfo.class, accountInfoDao);
        registerDao(QueueInfo.class, queueInfoDao);
        registerDao(QueueInfoBackup.class, queueInfoBackupDao);
        registerDao(QueueSetInfo.class, queueSetInfoDao);
        registerDao(ShopInfo.class, shopInfoDao);
    }
    
    public void clear() {
        accountInfoDaoConfig.clearIdentityScope();
        queueInfoDaoConfig.clearIdentityScope();
        queueInfoBackupDaoConfig.clearIdentityScope();
        queueSetInfoDaoConfig.clearIdentityScope();
        shopInfoDaoConfig.clearIdentityScope();
    }

    public AccountInfoDao getAccountInfoDao() {
        return accountInfoDao;
    }

    public QueueInfoDao getQueueInfoDao() {
        return queueInfoDao;
    }

    public QueueInfoBackupDao getQueueInfoBackupDao() {
        return queueInfoBackupDao;
    }

    public QueueSetInfoDao getQueueSetInfoDao() {
        return queueSetInfoDao;
    }

    public ShopInfoDao getShopInfoDao() {
        return shopInfoDao;
    }

}
