package com.smartqueue2.database.orm;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.smartqueue2.database.ormsql.QueueInfoBackup;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "QUEUE_INFO_BACKUP".
*/
public class QueueInfoBackupDao extends AbstractDao<QueueInfoBackup, Long> {

    public static final String TABLENAME = "QUEUE_INFO_BACKUP";

    /**
     * Properties of entity QueueInfoBackup.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property QueueName = new Property(1, String.class, "queueName", false, "QUEUE_NAME");
        public final static Property Num = new Property(2, int.class, "num", false, "NUM");
        public final static Property People = new Property(3, int.class, "people", false, "PEOPLE");
        public final static Property Phone = new Property(4, String.class, "phone", false, "PHONE");
        public final static Property Create = new Property(5, java.util.Date.class, "create", false, "CREATE");
        public final static Property State = new Property(6, int.class, "state", false, "STATE");
        public final static Property Count = new Property(7, int.class, "count", false, "COUNT");
    }


    public QueueInfoBackupDao(DaoConfig config) {
        super(config);
    }
    
    public QueueInfoBackupDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"QUEUE_INFO_BACKUP\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"QUEUE_NAME\" TEXT," + // 1: queueName
                "\"NUM\" INTEGER NOT NULL ," + // 2: num
                "\"PEOPLE\" INTEGER NOT NULL ," + // 3: people
                "\"PHONE\" TEXT," + // 4: phone
                "\"CREATE\" INTEGER," + // 5: create
                "\"STATE\" INTEGER NOT NULL ," + // 6: state
                "\"COUNT\" INTEGER NOT NULL );"); // 7: count
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"QUEUE_INFO_BACKUP\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, QueueInfoBackup entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String queueName = entity.getQueueName();
        if (queueName != null) {
            stmt.bindString(2, queueName);
        }
        stmt.bindLong(3, entity.getNum());
        stmt.bindLong(4, entity.getPeople());
 
        String phone = entity.getPhone();
        if (phone != null) {
            stmt.bindString(5, phone);
        }
 
        java.util.Date create = entity.getCreate();
        if (create != null) {
            stmt.bindLong(6, create.getTime());
        }
        stmt.bindLong(7, entity.getState());
        stmt.bindLong(8, entity.getCount());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, QueueInfoBackup entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String queueName = entity.getQueueName();
        if (queueName != null) {
            stmt.bindString(2, queueName);
        }
        stmt.bindLong(3, entity.getNum());
        stmt.bindLong(4, entity.getPeople());
 
        String phone = entity.getPhone();
        if (phone != null) {
            stmt.bindString(5, phone);
        }
 
        java.util.Date create = entity.getCreate();
        if (create != null) {
            stmt.bindLong(6, create.getTime());
        }
        stmt.bindLong(7, entity.getState());
        stmt.bindLong(8, entity.getCount());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public QueueInfoBackup readEntity(Cursor cursor, int offset) {
        QueueInfoBackup entity = new QueueInfoBackup( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // queueName
            cursor.getInt(offset + 2), // num
            cursor.getInt(offset + 3), // people
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // phone
            cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)), // create
            cursor.getInt(offset + 6), // state
            cursor.getInt(offset + 7) // count
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, QueueInfoBackup entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setQueueName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setNum(cursor.getInt(offset + 2));
        entity.setPeople(cursor.getInt(offset + 3));
        entity.setPhone(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCreate(cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)));
        entity.setState(cursor.getInt(offset + 6));
        entity.setCount(cursor.getInt(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(QueueInfoBackup entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(QueueInfoBackup entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(QueueInfoBackup entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
